# Generated by Django 4.2.20 on 2025-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='marketplace/media/img/categories'),
        ),
    ]
