# Generated by Django 4.2.20 on 2025-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='specification',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_range',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='New', max_length=16),
        ),
    ]
