# Generated by Django 4.2.20 on 2025-05-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media/img/categories'),
        ),
        migrations.AlterField(
            model_name='item_image',
            name='file',
            field=models.ImageField(upload_to='media/img/items'),
        ),
        migrations.AlterField(
            model_name='requestfile',
            name='file',
            field=models.FileField(upload_to='media/request_files/'),
        ),
    ]
