# Generated by Django 4.2.20 on 2025-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_item_category_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='test@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Empty', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='XXX XXXX XXX', max_length=255),
        ),
    ]
